### ISSUE TITLE
Licensing issue after project-config/sync to staging environment

### ISSUE THREAD

**Issue by bjrnblm** [nystudio107/craft-seomatic#420]
I bought the plugin on a `.localhost` environment where it works fine. Now I want to sync it to a staging and production server.

The staging & production have the following setting in `config/general.php`:
```
'allowAdminChanges' => false,
```

The plugin seemed to been installed without a problem during the deployment:
```
> ./craft project-config/sync --interactive 0
Installing plugin "seomatic" ... done
```

However I keep on getting this message:
> There’s a licensing issue with the SEOmatic plugin. Please fix on an environment where administrative changes are allowed.

The `project.yml` file seems to contain all the correct info, including the licenseKey (replaced by XXX):
```
seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
    licenseKey: XXX
    settings:
      pluginName: SEOmatic
      renderEnabled: true
      sitemapsEnabled: true
      regenerateSitemapsAutomatically: true
      headersEnabled: true
      environment: live
      displayPreviewSidebar: false
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      displayAnalysisSidebar: true
      devModeTitlePrefix: ''
      cpTitlePrefix: ''
      devModeCpTitlePrefix: ''
      separatorChar: '|'
      maxTitleLength: 70
      maxDescriptionLength: 155
      siteGroupsSeparate: '1'
      addHrefLang: true
      addXDefaultHrefLang: true
      generatorEnabled: true
```

Only difference I can find so far is in the `project.yml` the licenseKey is formatted as:
```
XXXX1234YYYY5678
```

However in the admin screen it's formatted as:
```
XXXX-1234-YYYY-5678
```

When i manually set my development machine to: `ENVIRONMENT="staging"` the plugin keeps on working.

However on the staging and production server the message keeps popping up. Should I do an other install step I missed or is this a bug?
